export const FETCH_USER_INFO_REQUEST = 'FETCH_USER_INFO_REQUEST';
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';
export const FETCH_USER_INFO_ERROR = 'FETCH_USER_INFO_ERROR';

export const FETCH_GROUP_BY_AREA_REQUEST = 'FETCH_GROUP_BY_AREA_REQUEST';
export const FETCH_GROUP_BY_AREA_SUCCESS = 'FETCH_GROUP_BY_AREA_SUCCESS';
export const FETCH_GROUP_BY_AREA_ERROR = 'FETCH_GROUP_BY_AREA_ERROR';

export const FETCH_EVENT_IN_AREA_REQUEST = 'FETCH_EVENT_IN_AREA_REQUEST';
export const FETCH_EVENT_IN_AREA_SUCCESS = 'FETCH_EVENT_IN_AREA_SUCCESS';
export const FETCH_EVENT_IN_AREA_ERROR = 'FETCH_EVENT_IN_AREA_ERROR';

export const FETCH_EVENT_REQUEST = 'FETCH_EVENT_REQUEST';
export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS';
export const FETCH_EVENT_ERROR = 'FETCH_EVENT_ERROR';

export const FETCH_USER_GROUPS_REQUEST = 'FETCH_USER_GROUPS_REQUEST';
export const FETCH_USER_GROUPS_SUCCESS = 'FETCH_USER_GROUPS_SUCCESS';
export const FETCH_USER_GROUPS_ERROR = 'FETCH_USER_GROUPS_ERROR';

export const FETCH_USER_EVENTS_REQUEST = 'FETCH_USER_EVENTS_REQUEST';
export const FETCH_USER_EVENTS_SUCCESS = 'FETCH_USER_EVENTS_SUCCESS';
export const FETCH_USER_EVENTS_ERROR = 'FETCH_USER_EVENTS_ERROR';

export const FETCH_GROUP_INFO_REQUEST = 'FETCH_GROUP_INFO_REQUEST';
export const FETCH_GROUP_INFO_SUCCESS = 'FETCH_GROUP_INFO_SUCCESS';
export const FETCH_GROUP_INFO_ERROR = 'FETCH_GROUP_INFO_ERROR';

export const FETCH_GROUP_EVENTS_REQUEST = 'FETCH_GROUP_EVENTS_REQUEST';
export const FETCH_GROUP_EVENTS_SUCCESS = 'FETCH_GROUP_EVENTS_SUCCESS';
export const FETCH_GROUP_EVENTS_ERROR = 'FETCH_GROUP_EVENTS_ERROR';

export const FETCH_ALL_SKILLS_REQUEST = 'FETCH_ALL_SKILLS_REQUEST';
export const FETCH_ALL_SKILLS_SUCCESS = 'FETCH_ALL_SKILLS_SUCCESS';
export const FETCH_ALL_SKILLS_ERROR = 'FETCH_ALL_SKILLS_ERROR';

export const FETCH_ALL_AREAS_REQUEST = 'FETCH_ALL_AREAS_REQUEST';
export const FETCH_ALL_AREAS_SUCCESS = 'FETCH_ALL_AREAS_SUCCESS';
export const FETCH_ALL_AREAS_ERROR = 'FETCH_ALL_AREAS_ERROR';

export const FETCH_EVENT_SKILLS_REQUEST = 'FETCH_EVENT_SKILLS_REQUEST';
export const FETCH_EVENT_SKILLS_SUCCESS = 'FETCH_EVENT_SKILLS_SUCCESS';
export const FETCH_EVENT_SKILLS_ERROR = 'FETCH_EVENT_SKILLS_ERROR';